### ISSUE TITLE
Various errors/warnings for Tado

### ISSUE THREAD

**Issue by 03397** [simonepsp/tado-ha#1]
Hey there during restart of Home Assistant I am getting the following warnings:

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:608
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 9:03:18 PM (3 occurrences)
Last logged: 9:03:18 PM

Sensor sensor.kitchen_ac has device class None, state class measurement and unit None thus indicating it has a numeric value; however, it has the non-numeric value: OFF (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Sensor sensor.master_bedroom_ac has device class None, state class measurement and unit None thus indicating it has a numeric value; however, it has the non-numeric value: OFF (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Sensor sensor.living_room_ac has device class None, state class measurement and unit None thus indicating it has a numeric value; however, it has the non-numeric value: OFF (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for tado using this method at custom_components/tado/__init__.py, line 96: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

In addition, I am getting the following messages during on/off, which I guess were there for debugging purposes. I do not think are needed anynore.

Logger: PyTado.interface
Source: custom_components/tado/__init__.py:301
Integration: Tado
First occurred: 9:05:43 PM (3 occurrences)
Last logged: 9:05:45 PM

{'type': 'MANUAL', 'setting': {'type': 'AIR_CONDITIONING', 'power': 'ON', 'mode': 'COOL', 'temperature': {'celsius': 23.0, 'fahrenheit': 73.4}, 'fanLevel': 'AUTO', 'verticalSwing': 'OFF', 'horizontalSwing': 'OFF', 'light': 'OFF'}, 'termination': {'type': 'MANUAL', 'typeSkillBasedApp': 'MANUAL', 'projectedExpiry': None}}
{'type': 'MANUAL', 'setting': {'type': 'AIR_CONDITIONING', 'power': 'ON', 'mode': 'COOL', 'temperature': {'celsius': 26.0, 'fahrenheit': 78.8}, 'fanLevel': 'AUTO', 'verticalSwing': 'OFF', 'horizontalSwing': 'OFF', 'light': 'OFF'}, 'termination': {'type': 'MANUAL', 'typeSkillBasedApp': 'MANUAL', 'projectedExpiry': None}}

Logger: PyTado.interface
Source: custom_components/tado/__init__.py:323
Integration: Tado
First occurred: 9:05:45 PM (1 occurrences)
Last logged: 9:05:45 PM

{'type': 'MANUAL', 'setting': {'type': 'AIR_CONDITIONING', 'power': 'OFF'}, 'termination': {'type': 'MANUAL', 'typeSkillBasedApp': 'MANUAL', 'projectedExpiry': None}}

**Comment by simonepsp** [comment]
My apologies but this project is discontinued. I'm transitioning my entire setup to an esphome ir blaster in a tiny package which I'm working on :) 

It was brought to my attention that the last update of HA breaks this custom component anyways.
AFAIK the tado component which the latest HA is shipped with works with Tado AC V3. It could be worth giving it a shot.

Please feel free to keep working on it or fork it and modify it as you please.
